using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using ManagerEmployee;

namespace Verdandi
{
    /// <summary>
    /// Lógica interna para WDCadastro.xaml
    /// </summary>
    public partial class WDCadastro : Window
    {
        public WDCadastro()
        {
            InitializeComponent();
            txb_nome.Focus();
        }

        public void AutoGeneratedColumns(object sender, System.EventArgs e)
        {
            dg_funcionario_cadastrado.Columns[0].Width = new(0.2, DataGridLengthUnitType.Star);
            dg_funcionario_cadastrado.Columns[1].Width = new(1, DataGridLengthUnitType.Star);
            dg_funcionario_cadastrado.Columns[1].Width = new(1, DataGridLengthUnitType.Star);
            dg_funcionario_cadastrado.Columns[1].Width = new(1, DataGridLengthUnitType.Star);
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            MainWindow mainWindow = new MainWindow();
            mainWindow.Show();
            this.Close();
        }

        private void btn_cadastrar_Click(object sender, RoutedEventArgs e)
        {
            List<Funcionario> novoFuncionario = new List<Funcionario>();

            Funcionario funcionario = new Funcionario();
            funcionario.nome = txb_nome.Text;
            funcionario.cpf = txb_cpf.Text;
            funcionario.telefone = txb_telefone.Text;
            funcionario.pix = txb_pix.Text;

            bool validador = funcionario.nome != string.Empty && funcionario.cpf != string.Empty && funcionario.telefone != string.Empty && funcionario.pix != string.Empty ? true : false;

            if (validador)
            {
                funcionario.Register();

                funcionario = funcionario.Filtra(funcionario.nome);

                novoFuncionario.Add(funcionario);

                dg_funcionario_cadastrado.ItemsSource = novoFuncionario;
                
                txb_nome.Text = string.Empty;
                txb_cpf.Text = string.Empty;
                txb_telefone.Text = string.Empty;
                txb_pix.Text = string.Empty;
            }
            else
                MessageBox.Show("Preencha todos os campos");
        }
    }
}
